//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClub.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int IDService { get; set; }
        public string NameService { get; set; }
        public decimal PriceService { get; set; }
        public Nullable<int> TimeService { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
    }
}
